POST http://127.0.0.1:8081/sessions
Content-Type: application/json

{
  "name": "Session"
}

###
POST http://127.0.0.1:8082/speakers
Content-Type: application/json

{
  "name": "Max"
}

###
GET http://127.0.0.1:8080/

###
POST http://127.0.0.1:8085/speakers
Content-Type: application/json

{
  "name": "Max"
}

###
POST http://127.0.0.1:8084/sessions
Content-Type: application/json

{
  "name": "Maximum!",
  "speakers": "Max!"
}

###
GET http://127.0.0.1:8083/

###
POST http://127.0.0.1:8088/speakers
Content-Type: application/json

{
  "name": "Max"
}

###
GET http://127.0.0.1:8087/sessions
Content-Type: application/json

###
POST http://127.0.0.1:8087/sessions
Content-Type: application/json

{
  "name": "Maximum!",
  "speakers": "Max!"
}

###
GET http://127.0.0.1:8086/

###
