version: '2.1'
networks:
  step8-all-in-one-k8s-skaffold:
    driver: bridge
services:
  postgres:
    image: postgres:alpine
    labels:
      MAINTAINER: Maksim Kostromin https://github.com/daggerok
    ports: ['5432:5432']
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    networks:
      step8-all-in-one-k8s-skaffold:
        aliases:
          - postgres
          - postgres.step8-all-in-one-k8s-skaffold
    healthcheck:
      retries: 15
      timeout: 3s
      interval: 3s
      test: pg_isready -h 127.0.0.1 -p $$POSTGRES_PORT -d $$POSTGRES_DB -U $$POSTGRES_USER
  sessions:
    image: daggerok/step8-all-in-one-k8s-skaffold-step8-sessions-rsocket-service:1.0.6
    labels:
      MAINTAINER: Maksim Kostromin https://github.com/daggerok
    # volumes: ['./step8-sessions-rsocket-service/target:/tmp']
    # entrypoint: ash -c 'java -jar /tmp/*.jar'
    ports: ['8102:8102']
    environment:
      SERVER_PORT: 8102
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      step8-all-in-one-k8s-skaffold:
        aliases:
          - step8-sessions-rsocket-service
          - step8-sessions-rsocket-service.step8-all-in-one-k8s-skaffold
    healthcheck:
      retries: 15
      timeout: 3s
      interval: 3s
      test: wget --quiet --tries=1 --spider http://127.0.0.1:$$SERVER_PORT/actuator/health || exit
  speakers:
    image: daggerok/step8-all-in-one-k8s-skaffold-step8-speakers-rest-api-service:1.0.6
    labels:
      MAINTAINER: Maksim Kostromin https://github.com/daggerok
    #volumes: ['./step8-speakers-rest-api-service/target:/tmp']
    #entrypoint: ash -c 'java -jar /tmp/*.jar'
    ports: ['8103:8103']
    environment:
      SERVER_PORT: 8103
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      step8-all-in-one-k8s-skaffold:
        aliases:
          - step8-speakers-rest-api-service
          - step8-speakers-rest-api-service.step8-all-in-one-k8s-skaffold
    healthcheck:
      retries: 15
      timeout: 3s
      interval: 3s
      test: wget --quiet --tries=1 --spider http://127.0.0.1:$$SERVER_PORT/actuator/health || exit
  frontend:
    image: daggerok/step8-all-in-one-k8s-skaffold-step8-frontend:1.0.6
    labels:
      MAINTAINER: Maksim Kostromin https://github.com/daggerok
    #volumes: ['./step8-frontend/target:/tmp']
    #entrypoint: ash -c 'java -jar /tmp/*.jar'
    ports: ['8101:8101']
    environment:
      SERVER_PORT: 8101
      SESSIONS_HOST: step8-sessions-rsocket-service
      SESSIONS_PORT: 8102
      SPEAKERS_HOST: step8-speakers-rest-api-service
      SPEAKERS_PORT: 8103
    depends_on:
      sessions:
        condition: service_healthy
      speakers:
        condition: service_healthy
    networks:
      step8-all-in-one-k8s-skaffold:
        aliases:
          - step8-frontend
          - step8-frontend.step8-all-in-one-k8s-skaffold
    healthcheck:
      retries: 15
      timeout: 3s
      interval: 3s
      test: wget --quiet --tries=1 --spider http://127.0.0.1:$$SERVER_PORT/actuator/health || exit
  healthcheck: # really, not needed, just for CI in our case...
    image: busybox
    depends_on:
      frontend:
        condition: service_healthy
