CREATE SCHEMA IF NOT EXISTS public;
DROP TABLE IF EXISTS speakers;
CREATE TABLE speakers (
    id UUID NOT NULL DEFAULT RANDOM_UUID(),
    name VARCHAR NOT NULL,
    CONSTRAINT speakers_pk PRIMARY KEY (id)
);
